### ISSUE TITLE
支不支持多子表join？

### ISSUE THREAD

**Issue by jmbkeyes** [cetus-tools/cetus#185]
有两张表A， B， 他们都是大数据表，将他们按各自的分表键分表之后变成了A_0, A_1, B_0， B_1.
select a.name, b.name as n2
from A a
INNER JOIN B b on a.xx= b.yyy
where a.shardingKey=xxx and b.shardingKey=yyy
使用中间件cetus之后会不会生成子表联合查询sql呢？
(e.g. select a.name, b.name as n2 from A_0 a inner join B_1 b on a.xx=b.yyy)

**Comment by wangbin579** [comment]
一个分片键规则对应一个vdb，多个分片键join就不支持了，跟分库一个道理
