### ISSUE TITLE
启动时候错误 请问是配置有问题？

### ISSUE THREAD

**Issue by java-fei** [cetus-tools/cetus#186]
![image](https://user-images.githubusercontent.com/16696899/57191217-8c676380-6f55-11e9-8173-3cd04b6e38b3.png)
![image](https://user-images.githubusercontent.com/16696899/57191222-9c7f4300-6f55-11e9-9ea8-20a7bbd483b5.png)

**Comment by tsthght** [comment]
在centos6.6上使用启动命令并没有复现： ./bin/cetus --defaults-file=conf/proxy.conf --conf-dir=/home/gaohaitao/cetus_install/conf/
![image](https://user-images.githubusercontent.com/13314548/57191866-cab45100-6f5c-11e9-888f-233fb287340e.png)

麻烦提供下您的操作系统详细版本/启动Cetus的命令等更详尽信息，方便我们复现和排查
