### ISSUE TITLE
分表分库安装报错

### ISSUE THREAD

**Issue by gaochenfeng** [cetus-tools/cetus#187]
In file included from /data/cetus-2.2.7/src/network-mysqld-packet.c:29:0:
/data/cetus-2.2.7/src/network-mysqld-packet.c: In function ‘network_mysqld_proto_get_com_query_result’:
/data/cetus-2.2.7/src/network-mysqld-packet.h:103:36: error: ‘SERVER_MORE_RESULTS_EXIST’ undeclared (first use in this function)
 #define SERVER_MORE_RESULTS_EXISTS SERVER_MORE_RESULTS_EXIST
                                    ^
/data/cetus-2.2.7/src/network-mysqld-packet.c:98:50: note: in expansion of macro ‘SERVER_MORE_RESULTS_EXISTS’
                 if (!(ok_packet->server_status & SERVER_MORE_RESULTS_EXISTS)) {
                                                  ^
/data/cetus-2.2.7/src/network-mysqld-packet.h:103:36: note: each undeclared identifier is reported only once for each function it appears in
 #define SERVER_MORE_RESULTS_EXISTS SERVER_MORE_RESULTS_EXIST
                                    ^
/data/cetus-2.2.7/src/network-mysqld-packet.c:98:50: note: in expansion of macro ‘SERVER_MORE_RESULTS_EXISTS’
                 if (!(ok_packet->server_status & SERVER_MORE_RESULTS_EXISTS)) {
                                                  ^
/data/cetus-2.2.7/src/network-mysqld-packet.c: In function ‘network_mysqld_proto_get_query_result’:
/data/cetus-2.2.7/src/network-mysqld-packet.c:685:10: error: ‘COM_SHUTDOWN’ undeclared (first use in this function)
     case COM_SHUTDOWN:
          ^
make[2]: *** [src/CMakeFiles/mysql-chassis-proxy.dir/network-mysqld-packet.c.o] Error 1
make[1]: *** [src/CMakeFiles/mysql-chassis-proxy.dir/all] Error 2

**Comment by wangbin579** [comment]
需要按照 https://github.com/cetus-tools/cetus/blob/master/doc/cetus-install.md 来安装，切记不要在MySQL 8环境下安装

**Comment by gaochenfeng** [comment]
谢谢，mysql5.7已安装成功，mysql8 报错
