### ISSUE TITLE
cetus 后端state 一直是unknown

### ISSUE THREAD

**Issue by bayannur** [cetus-tools/cetus#195]
cetus日志报错
(Critical) Could not connect to Backend xxx@xxxx
(Critical) monitor thread cannot connect to backend: xxx@xxx
检查sharding.json、users.json、shard.conf文件没有发现问题，mysql 实例用户权限也正确。

**Comment by bayannur** [comment]
经过分析，编译cetus时，使用了inception版本的lib库。改用官方mysql lib包，重新编译cetus，解决问题。

**Comment by zzg-988** [comment]
1、cetus编译完成后，启动cetus时报错：error while loading shared libraries: libmysqlclient.so.18: cannot open shared object file: No such file or directory
2、然后建软连接ln -s   /usr/lib64/libmysqlclient.so.18 -> /path/mysql/lib/libmysqlclient.so.18，成功启动；
cetus日志报错
(Critical) Could not connect to Backend xxx@xxxx
(Critical) monitor thread cannot connect to backend: xxx@xxx
一直没有找到解决办法，在网易团队的帮助下找到了原因：编译cetus时，使用了inception版本的lib库
3、后来用官方mysql lib包或者重新ln -s 到mariadb-10.1.19，问题解决；
感谢网易团队的给力的支持！！！

**Comment by wangriyu** [comment]
这个问题的具体解决办法是啥，咋使用官方 lib 包
