### ISSUE TITLE
建议作者创建一个Pinned issues 这样也能让大家知道都那些公司在用这个工具

### ISSUE THREAD

**Issue by zhangleijie** [cetus-tools/cetus#204]
Pinned issues
The list of **** users (*****用户列表）

**Comment by lazio579** [comment]
为公司隐私考虑，没有加上这个。

读写分离版本目前非常稳定；分库版本因为MySQL自身xa bug，不建议使用（后续会有分布式数据库产品来代替），当然能够承受MySQL自身bug，那就没有多少稳定性问题。

**Comment by zhangleijie** [comment]
cetus 以后的roadmap路线是主攻读写分离版吗， 分库版是以后商业公司提供........
